FROM golang:latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
 COPY . .
RUN go build -o todomain .
CMD ["./todomain"]
EXPOSE 8000 
# This Dockerfile sets up a Go application in a container.